### ISSUE TITLE
missing base image and base-pro image

### ISSUE THREAD

**Issue by bjwswang** [kubebb/component-store#6]
To build this lowcode component image, we need these base images.

**Comment by dayuy** [comment]
> To build this lowcode component image, we need these base images.

base image: `172.22.96.119/front-end/component-store:base-0.1`
base-pro image: `172.22.96.119/front-end/component-store:base-0.1-prod`
latest image: `172.22.50.223/kubebb/component-store:v0.1.3.08241813`

**Comment by dayuy** [comment]
Refer to GitHub Action

**Comment by Carrotzpc** [comment]
revert #101
